spring:
  application:
    name: discoveryserver
  management:
    endpoints:
      web:
        exposure:
          include: "prometheus"
    metrics:
      export:
        prometheus:
          enabled: true
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  instance:
    hostname: localhost
server:
  port: 9000
